version: 2.1

  jobs:
    build:
      docker:
        -image: circleci/node:latest 
      working_directory: ~/repo
      step:
       - checkout
       - run:
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
